server:
  port: 8080

database:
  mongodb:
    uri: "mongodb://localhost:27017"
    dbname: "linkedin_scraper"

redis:
  addr: "localhost:6379"

scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
  concurrent_requests: 5